---
title: "cluster"
format: html
---

```{r}
library(tidyverse)
library(sf)
library(ineapir)

```

## Cálculo de la distancia al mar

Datos obtenidos del CNIC
```{r}


municipios_shape <- st_read("data/cnig/lineas_limite/SHP_ETRS89/recintos_municipales_inspire_peninbal_etrs89/recintos_municipales_inspire_peninbal_etrs89.shp") |> 
    st_transform(25830)

l_costa <- st_read("data/costa/COSTA.shp") |> 
    filter(BAJAMAR == TRUE & CIERRACOST == TRUE) |> 
    st_transform(25830) |> 
    st_union() |> 
     st_line_merge()


    
datos_municipios <- municipios_shape |>
    filter(CODNUT2 == "ES52") |>            # Select CV
    mutate(
        geometry = geometry,
        name = NAMEUNIT,                    # Mantener nombre
        ine_code = substr(NATCODE, 7, 11),  # Transform to INE code
        distancia_mar = ifelse(
            st_intersects(geometry, l_costa, sparse = FALSE)[,1],
            0,  # Si toca la costa (distancia = 0)
            st_distance(st_centroid(geometry), l_costa)  
            ),
        .keep = "none"  
        ) 

```

# Datos de Renta y de población

```{r}

ultimo_anyo_renta <- 2022
tipo_renta_seleccionada <- "Renta neta media por hogar"

# Dado el ID de la tabla del INE obtiene la renta media por hogar de dicha tabla
get_renta_INE <- function(id_table){
    
    data <- get_data_table(idTable=id_table, unnest = TRUE, tip="AM", metanames = TRUE, metacodes = TRUE) 
    
      return(data |>
                filter(
                        nchar(Unidades.territoriales.Codigo) == 5 & 
                        Anyo == ultimo_anyo_renta &
                        Indicadores.de.renta.media.y.mediana ==tipo_renta_seleccionada
                      ) |>
                select(
                      ine_code =Unidades.territoriales.Codigo,
                      renta = Valor
                      )
      )
         
}


# Tarda bastante rato
rentas <- bind_rows(
        get_renta_INE(31250),
        get_renta_INE(30833),
        get_renta_INE(30962)
    )



# Población

ultimo_anyo_poblacion <- 2024
poblacion <

get_renta_INE <- function(id_table){
    
    data <- get_data_table(idTable=id_table, unnest = TRUE, tip="AM", metanames = TRUE, metacodes = TRUE) 
    
      return(data |>
                filter(
                        nchar(Unidades.territoriales.Codigo) == 5 & 
                        Anyo == ultimo_anyo_renta &
                        Indicadores.de.renta.media.y.mediana ==tipo_renta_seleccionada
                      ) |>
                select(
                      ine_code =Unidades.territoriales.Codigo,
                      renta = Valor
                      )
      )
         
}



datos_municipios <- full_join(datos_municipios,rentas,by="ine_code")
   



```